# Generated by Django 3.2.7 on 2021-11-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('link', models.CharField(max_length=300, verbose_name='Ссылка')),
                ('pubDate', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование предприятия')),
                ('address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('telephone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Адрес э/почты')),
                ('insta', models.CharField(max_length=250, verbose_name='Ссылка на Instagram аккаунт')),
            ],
        ),
    ]
