# Generated by Django 3.2.7 on 2021-11-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_newstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.newstype', verbose_name='Тип'),
        ),
    ]
