# Generated by Django 3.2.7 on 2021-11-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_news_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование предприятия'),
        ),
    ]
