# Generated by Django 3.2.7 on 2021-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='short_name',
            field=models.CharField(default='', max_length=50, verbose_name='Краткое наименование'),
            preserve_default=False,
        ),
    ]
