# Generated by Django 3.2.7 on 2021-11-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_org_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('release_date', models.DateTimeField(verbose_name='Дата релиза')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.program', verbose_name='Программа')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_type',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
    ]
