# Generated by Django 3.2.7 on 2021-11-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20211103_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Releases',
            new_name='Release',
        ),
    ]
