# Generated by Django 3.2.7 on 2021-11-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_release_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='price_list_name',
            field=models.CharField(default='', max_length=200, verbose_name='Наименование файла с прайс-листом'),
            preserve_default=False,
        ),
    ]
