# Generated by Django 3.2.7 on 2021-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_org_price_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='price_list_name',
            field=models.FileField(upload_to='pricelists/%m-%Y'),
        ),
    ]
