# Generated by Django 3.2.7 on 2021-12-21 07:24

from django.db import migrations, models
import info.validators


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_rename_price_list_name_org_price_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/', validators=[info.validators.validate_file_extension])),
                ('link', models.CharField(max_length=300, verbose_name='Ссылка')),
                ('active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
        ),
    ]
