# Generated by Django 3.2.7 on 2021-12-23 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть введен в формате: +71234567890 или 81234567890 или 123456', regex='^(\\+7|8)9\\d{9}$|^\\d{6}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='org',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес э/почты'),
        ),
        migrations.AlterField(
            model_name='org',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть введен в формате: +71234567890 или 81234567890 или 123456', regex='^(\\+7|8)9\\d{9}$|^\\d{6}$')], verbose_name='Номер телефона'),
        ),
    ]
